[supervisord]
nodaemon=true
logfile=/dev/null              ; Отключаем запись основного лога Supervisord
# logfile_maxbytes=0             ; Отключаем ограничение размера логов

[program:listener]
command=python3 /app/listener.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:cron]
command=/app/start_cron.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
